version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db   

  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
